### ISSUE TITLE
BUG - https://jhub-apps.vercel.app/ link in Jhub-apps about section on github doesn't load

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/jhub-apps#109]
### Context

Reporting a bug:
![image](https://github.com/nebari-dev/jhub-apps/assets/23342526/2142b24b-7298-4057-b3d1-d75ac33e3939)

### Value and/or benefit

fix a bug

**Comment by aktech** [comment]
Thanks @Adam-D-Lewis for pointing that. I think I added the vercel link too early. It's still a work in progress: https://github.com/nebari-dev/jhub-apps/tree/vercel

**Comment by jbouder** [comment]
The above update should provide the base loading functionality. This should be ready to close.

**Comment by Adam-D-Lewis** [comment]
Looks like it works now!  I'll close the issue.
