### ISSUE TITLE
[BUG] Stop ability of starting stopped shared apps from JupyterHub interface

### ISSUE THREAD

**Issue by aktech** [nebari-dev/jhub-apps#138]
### Context

Here is the scenario, when a user creates an app and it's stopped over time and an admin user, who can see the shared app clicks on the app, the user is redirected to JupyterHub's interface to start the app, which calls the jupyterhub API directly instead of going via jhub-apps service, which ends up with following:

- creating a jupyterlab as it uses the default spawner
- loses all the `user_options` set by jhub-apps
- Gets disappeared from the app launcher home as only the apps with `users_options['jhub_app'] = True` are shown in the app launcher home.

Stopped shared app should only be started from this interface
![image](https://github.com/nebari-dev/jhub-apps/assets/5647941/b31075cf-5454-4401-a8db-73eee388a2e9)

We need to somehow disable starting from the jupyterhub UI

### Value and/or benefit

- Ability to only create app from one interface
- Consistency in app creation

**Comment by krassowski** [comment]
Currently the user who sees such an app is unable to "Start" it from dropdown:

![image](https://github.com/nebari-dev/jhub-apps/assets/5832902/93894b39-c099-47b5-9e28-246b5cfc8f12)

That `Start` would go post to `/server/` endpoint which currently has no parameters so it does not allow to start a specifc server, just the default server of a given user:

https://github.com/nebari-dev/jhub-apps/blob/de8dae692f650e8ac98bbfde41f4a713878f65cc/jhub_apps/service/routes.py#L161-L181

I guess that once we implement the new parameter in `/server/` we could then change the main card link to a programmatic call to `/server` and then only redirect to the link location once the server reports back as running. Does it sound like a good plan?

**Comment by aktech** [comment]
This is already addressed.
