### ISSUE TITLE
[MVP] Dashboard Apps JupyterHub Extension 

### ISSUE THREAD

**Issue by aktech** [nebari-dev/jhub-apps#2]
### Value and/or benefit

The CDSDashboards extension is not compatible with current versions of JupyterHub (it requires JupyterHub < 2.0). People using Nebari won't be able to use CDS Dashboard in the future release, hence there is an urgent need to create a solution for the same. The goal here is to create a replacement for CDS Dashboard. This is a relatively larger project and here we'll define the scope for the MVP (4-6 week half-time):

A JupyterHub Extension to create and share dashboards that supports the following:

- Works with single server JupyterHub
- Supports the following dashboard frameworks (ability to create dashboards):
	- Plotly
	- Streamlit
	- Panel
	- Bokeh
	- Voila
- Lists available dashboards
- Shareable: Dashboard running as the user who shared (No Auth)

### Long term goals/questions

- Dashboard - Plotly, streamlit, Panel, Bokeh
- Share to group/access management - not as important
- Dashboard running as user who shared
- Long running dashboards / dashboard restart is important
- Environments management, done manually.
- Adding logs & error messages
- Add debug modes for things like plotly
- Launch modes & bringing down costs.
- idle -culler + restart when accessed
- Avoid 1-1 correspondence between pods and dashboards. Shared/oversubscribed pods.
- Can we launch multiple dashboards on the same pod.
- Log max cpu & max memory used by a dashboard so you can decide how to right size the pod.
- Decide where to store state, how will restarts happen, can we upgrade jhub without losing dashboards. Which dashboards are available, which are running etc.
- Listing of Available Dashboards
- Dashboards accessible to the public without authentication

**Comment by aktech** [comment]
Some wireframes:

![JupyterHubApps1](https://github.com/nebari-dev/jhub-apps/assets/5647941/117c0ebb-e0a6-4565-942f-40fd30fb589d)
![JupyterHubApps2](https://github.com/nebari-dev/jhub-apps/assets/5647941/76617390-ceca-45c3-bd5d-7c0750c52895)
![JupyterHubApps3](https://github.com/nebari-dev/jhub-apps/assets/5647941/70884ccb-dcaa-4be3-9605-e19cfc385d5b)
![JupyterHubApps4](https://github.com/nebari-dev/jhub-apps/assets/5647941/f671400e-512f-4ca9-a561-b7723aec9990)

**Comment by aktech** [comment]
- Add Edit Dashboard
- Conda Environment in Create Dashboard

**Comment by tylerpotts** [comment]
@aktech This all looks great! Thanks for writing it up.

**Comment by aktech** [comment]
This is done now.
