### ISSUE TITLE
[DOC] - Add specific instructions for Streamlit and Voila

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/jhub-apps#256]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

We need examples and any specific instructions for creating apps with Voila and Streamlit.

Ref: #222 adds these for Bokeh, Panel, and Gradio

### Steps to Resolve this Issue

N/A

**Comment by ericdatakelly** [comment]
@pavithraes @kcpevey Ready for review: #269
