### ISSUE TITLE
[ENH] - Increase h1 margins

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/jhub-apps#341]
### Feature description

Increasing the top and bottom margins for h1 will be nicer in the Login & Server options page

Currently the text seems very close to the top navbar:

<img width="1330" alt="Screenshot 2024-06-14 at 12 17 19 AM" src="https://github.com/nebari-dev/jhub-apps/assets/33131404/8fbeed04-c193-491c-93c4-ea57ead1347e">

<img width="595" alt="Screenshot 2024-06-14 at 12 17 36 AM" src="https://github.com/nebari-dev/jhub-apps/assets/33131404/fa72900e-afe7-4fb7-b523-44da643a65d5">

### Value and/or benefit

Visual nicety

### Anything else?

I think the relevant section to be updated is:

https://github.com/nebari-dev/jhub-apps/blob/43fcc8c0cf1086b2251a77387b80a595eefba499/jhub_apps/templates/style.css#L54-L65

In the old theme, 30px was set, ref: https://github.com/nebari-dev/nebari-jupyterhub-theme/blob/dbfa10e9ca071ed0c5e5015442faaba4ee3c1285/nebari_jupyterhub_theme/templates/style.css#L74-L78

**Comment by jbouder** [comment]
This is issue should be resolved, and I believe was related to the Bootstrap upgrade. It looks like you're running an older version of the app launcher based on a few things. This is the change that fixed it: https://github.com/nebari-dev/jhub-apps/commit/9c70cbf6abfe08b5a10a513ef4197364e3aa86a8#diff-323f0362761d127917ab6d95526774b20c29df50ce9c25da35cffa14b28d0ed0R374

Here is what it looks like now.
<img width="1728" alt="Screenshot 2024-06-17 at 8 33 02 AM" src="https://github.com/nebari-dev/jhub-apps/assets/61591423/64a2250e-35f2-42fa-81b2-44bf3e729d88">
<img width="1716" alt="Screenshot 2024-06-17 at 8 33 17 AM" src="https://github.com/nebari-dev/jhub-apps/assets/61591423/29f98e6e-2fb6-4823-8b0a-ca8238b2c660">
