### ISSUE TITLE
Link to create form docs does not work

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jhub-apps#354]
### Context

> Begin your project by entering the details below. For more information about creating an app, [visit our docs](https://jhub-apps.nebari.dev/docs/reference/create-app-form).

https://jhub-apps.nebari.dev/docs/reference/create-app-form gives "Page Not Found"

### Value and/or benefit

NA

**Comment by krassowski** [comment]
https://github.com/nebari-dev/jhub-apps/blob/6e6ad754d9a99e8ae98b3137f1c0c19deff118c4/ui/src/pages/create-app/create-app.tsx#L31-L42

**Comment by krassowski** [comment]
I guess it should point to https://jhub-apps.nebari.dev/docs/category/create-apps?

**Comment by aktech** [comment]
>I guess it should point to [jhub-apps.nebari.dev/docs/category/create-apps](https://jhub-apps.nebari.dev/docs/category/create-apps)?

Makes sense.
