### ISSUE TITLE
Opening a stopped shared app causes infinite loading

### ISSUE THREAD

**Issue by aktech** [nebari-dev/jhub-apps#534]
### Context

When you try opening a shared app which is stopped by directly going to the URL it gets stuck on loading infinitely.

Steps to reproduce:

1. Alice creates an app named awesome-app and shares it with Bob
2. Alice stops the app
3. Bob has the url of the app, lets say http://<hub>/hub/user/alice/panel-share-48e7de5/, when Bob visits the app, directly via the url, he sees an infinitely loading spinner.

Ideally a modal should open asking if the user wants to start the app, just like it happens when you click on the stopped app card in the UI.

See relevant comments:
- https://github.com/nebari-dev/jhub-apps/pull/533#issuecomment-2489341579
- https://github.com/nebari-dev/jhub-apps/pull/533#issuecomment-2489360023

### Value and/or benefit

A nicer UX

**Comment by aktech** [comment]
cc @jbouder @kildre

**Comment by jbouder** [comment]
> cc @jbouder @kildre

@aktech , I created a PR to fix the infinite loading issue. Essentially the page was expecting the api response to include form data, which it does not, given the current API returns a 404. In order to fix the issue I added some error handling.

That said, as i mentioned the api call currently returns a 404, which may or may not be the expected behavior...this may need to be addressed if not. Also, the current implementation does not allow a non-owner to start an app, so opening the start modal doesn't make sense here.

**Comment by kildre** [comment]
@jbouder I created a ticket to give shared user the ability to Start/Stop shared server/app, I'll work on this right away:
https://gitlab.jatic.net/jatic/team-metrostar/t-e-platform/-/issues/862

cc @aktech

**Comment by aktech** [comment]
>@aktech , I created a PR to fix the infinite loading issue. Essentially the page was expecting the api response to include form data, which it does not, given the current API returns a 404. In order to fix the issue I added some error handling.

I think error handling makes sense.

>That said, as i mentioned the api call currently returns a 404, which may or may not be the expected behavior...this may need to be addressed if not.



Also, the current implementation does not allow a non-owner to start an app, so opening the start modal doesn't make sense here.

**Comment by aktech** [comment]
>That's the expected behaviour as the user doesn't owns the app the API doesn't return app details for it with that url.


Also, the API call from frontend is: 

http://127.0.0.1:8000/services/japps/server/panel-share-48e7de5

This doesn't tells the owner in the url (nor in query params),  so there is no way for backend to know which user this app belongs to and hence unable to fetch details for that app.

We can make the API return app details if we pass in owner (via query param) in this API call.

**Comment by jbouder** [comment]
> > @aktech , I created a PR to fix the infinite loading issue. Essentially the page was expecting the api response to include form data, which it does not, given the current API returns a 404. In order to fix the issue I added some error handling.
> 
> I think error handling makes sense.
> 
> > That said, as i mentioned the api call currently returns a 404, which may or may not be the expected behavior...this may need to be addressed if not.
> 
> That's the expected behaviour as the user doesn't owns the app the API doesn't return app details for it with that url.
> 
> > Also, the current implementation does not allow a non-owner to start an app, so opening the start modal doesn't make sense here.
> 
> This is not the expected behaviour. The backend allows this. The frontend shouldn't be checking the permissions, anyone can start a shared app given they have permissions and checking that is backend's responsibility. UI should rely on API response to infer if the user has permissions or not.

In reference to the last point...it looks like Kilian is working on an update to allow a non-owner to start, so I assume nothing more to do right now on my end.

**Comment by jbouder** [comment]
> > That's the expected behaviour as the user doesn't owns the app the API doesn't return app details for it with that url.
> 
> Also, the API call from frontend is:
> 
> http://127.0.0.1:8000/services/japps/server/panel-share-48e7de5
> 
> This doesn't tells the owner in the url (nor in query params), so there is no way for backend to know which user this app belongs to and hence unable to fetch details for that app.
> 
> We can make the API return app details if we pass in owner (via query param) in this API call.

In reference to this issue, I can't see a situation where a non-owner would navigate directly to the app, and have the owner details to pass to the API. Am I missing something here?

**Comment by aktech** [comment]
>In reference to this issue, I can't see a situation where a non-owner would navigate directly to the app

A user ca bookmark a shared app, then they can directly go that app via url.

> and have the owner details to pass to the API. Am I missing something here?

The app url is something like this: http://127.0.0.1:8000/hub/user/aktech/panel-share-48e7de5/

then frontend makes a call to backend with: http://127.0.0.1:8000/services/japps/server/panel-share-48e7de5

This makes backend return 404, when say Alice is requesting aktech's server as the default owner is the user who makes the call and the default user doesn't owns that server.

**Comment by jbouder** [comment]
> > In reference to this issue, I can't see a situation where a non-owner would navigate directly to the app
> 
> A user ca bookmark a shared app, then they can directly go that app via url.
> 
> > and have the owner details to pass to the API. Am I missing something here?
> 
> The app url is something like this: http://127.0.0.1:8000/hub/user/aktech/panel-share-48e7de5/
> 
> then frontend makes a call to backend with: http://127.0.0.1:8000/services/japps/server/panel-share-48e7de5
> 
> This makes backend return 404, when say Alice is requesting aktech's server as the default owner is the user who makes the call and the default user doesn't owns that server.

Yup, I get the bookmark thing. And now that I think of it, I can get the owner from the server URL, but what should I then do with that? The GET call is still going to return a 404, which means I won't know the actual status of the server. So I can't tell if its started, stopped, etc.

That said, I'm think I'm getting lost in the conversation :D...I might need you to just spell out what you suggest I updated and I can do a deeper dive.

**Comment by aktech** [comment]
If the frontend can send the owner in the get request, we can update the backend to return the server details and then frontend will know the actual status of the server, which means we can have the same behaviour (in going via bookmark link) as we have when some one clicks on the app card when app is not running.

Your PR is definitely an improvement from the current situation, so I am going to merge it, we can implement the above in a follow up PR as that requires backend change as well.

**Comment by jbouder** [comment]
> If the frontend can send the owner in the get request, we can update the backend to return the server details and then frontend will know the actual status of the server, which means we can have the same behaviour (in going via bookmark link) as we have when some one clicks on the app card when app is not running.
> 
> Your PR is definitely an improvement from the current situation, so I am going to merge it, we can implement the above in a follow up PR as that requires backend change as well.

That makes sense. I'll coordinate with @kildre on who will work that update.

**Comment by aktech** [comment]
Awesome, sounds great! 🎉
