### ISSUE TITLE
[BUG] Repository options not sent when creating app with server options

### ISSUE THREAD

**Issue by aktech** [nebari-dev/jhub-apps#542]
### Context

Looks like repository options are not sent by frontend when creating app with server options.

<img width="1512" alt="server-options" src="https://github.com/user-attachments/assets/51af0d08-c8a3-4fdc-805e-23dab1f02106">

cc @jbouder @kildre 

Sample payload (sent via when creating app from repo):

```json
{
  "servername": "My Panel App (Git)",
  "user_options": {
    "jhub_app": true,
    "display_name": "My Panel App (Git)",
    "description": "This is a panel app created from git repository",
    "framework": "panel",
    "thumbnail": "",
    "filepath": "panel_basic.py",
    "conda_env": "jhub-apps-dev",
    "env": {
      "SOMETHING_FOO": "bar",
      "SOMETHING_BAR": "beta"
    },
    "custom_command": "",
    "profile": "",
    "public": false,
    "share_with": {
      "users": [],
      "groups": []
    },
    "keep_alive": false
  }
}
```

This can be reproduced by uncommenting this piece of code:
https://github.com/nebari-dev/jhub-apps/blob/9392e7eb489853b51c5eb08c963ca478e95daeb9/jupyterhub_config.py#L94-L101

### Value and/or benefit

Being able to deploy app from repo with server options.

**Comment by jbouder** [comment]
Assuming I understand the issue, this should be fixed in the PR above.
