### ISSUE TITLE
[ENH] - Tweak design of cards?

### ISSUE THREAD

**Issue by dharhas** [nebari-dev/jhub-apps#62]
### Feature description

Now that I have been playing around with the deployed versions I have some comments.

- There is a lot of unused whitespace in the app cards.
- Not sure about the grey background behind the thumbnails 
- This looks even more unbalanced when no description is provided. Should we consider default description text? i.e. "This is a panel app created by aktech" or make it a hover feature etc?
- Location of the "author" section changes when there is no description
- The app card are quite large so less are visible at a time

![image](https://github.com/nebari-dev/jhub-apps/assets/561301/89887bb2-48cb-44f7-9d67-f6748c7d8c78)

for a reference of another way of doing it (not saying we should follow this)

![image](https://github.com/nebari-dev/jhub-apps/assets/561301/e97b4e13-daf2-4c2b-a0aa-eac09c8364d6)

ref: https://huggingface.co/spaces

### Value and/or benefit

Better aesthetics and fit more cards on the screen at once.

cc: @smeragoel @jbouder

### Anything else?

This is for after the current Milestone. Nothing to do immediately.

**Comment by smeragoel** [comment]
Cool, I'll do some preliminary research to improve the design of the cards. Let me know when I should start working on it actively!
