### ISSUE TITLE
[BUG] - Editing an app removes existing thumbnail

### ISSUE THREAD

**Issue by dharhas** [nebari-dev/jhub-apps#64]
### Context

If I edit a deployed app which has a thumbnail, the edit form shows:

![image](https://github.com/nebari-dev/jhub-apps/assets/561301/0332c0d8-45ab-40e8-aceb-1d9e52e65648)

Which can be ok since I'm not planning on choosing a new thumbnail. But when I hit save I lose my old thumbnail and it defaults to the default thumbnail for that kind of app.

The behavior I expect is that the existing thumbnail stays in place unless a new one is uploaded.

Nice to have:
- show existing thumbnail in the edit form

### Value and/or benefit

I wouldn't keep accidentally deleting my app thumbnail when I am editing other parts of the App settings.

note: we do not need to fix this for the 2024.1.1 milestone.

cc: @jbouder

**Comment by jbouder** [comment]
In addition to fixing this issue, I also suggest that we create a design for an overall nicer Thumbnail component. We went with the default file as a short term solution.

**Comment by jbouder** [comment]
This new component needs to account for things like, adding a thumbnail, loading an existing thumbnail, which is base64 encoded, and removing/updating a thumbnail.

**Comment by aktech** [comment]
Also, note that the thumbnail solution we have currently is just base64 encoded image stored as string in the JupyterHub database (in `user_options`), we would need to move towards a better solution long term, i.e. not storing images in the DB.

**Comment by jbouder** [comment]
The above update should resolve this issue. This should be ready to close.

**Comment by jbouder** [comment]
This has been resolved
