### ISSUE TITLE
[DOC] - Document gradio app creation

### ISSUE THREAD

**Issue by aktech** [nebari-dev/jhub-apps#78]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Document creation of gradio app, the requirement is it must accept the following params:

- `--server-port`
- `--root-path`

This can be easily achieved by using `click` or `argparse` as shown in the [example gradio app](https://github.com/nebari-dev/jhub-apps/blob/fe69499312b20f08702112ebe1f398ea182e510a/jhub_apps/examples/gradio_basic.py#L13).

https://github.com/nebari-dev/jhub-apps/blob/fe69499312b20f08702112ebe1f398ea182e510a/jhub_apps/examples/gradio_basic.py#L13-L17

Currently it's not documented except in the [example itself](https://github.com/nebari-dev/jhub-apps/blob/fe69499312b20f08702112ebe1f398ea182e510a/jhub_apps/examples/gradio_basic.py#L13).

**Comment by kcpevey** [comment]
This is complete - https://jhub-apps.nebari.dev/docs/create-apps/gradio-app
