### ISSUE TITLE
[ENH] - Ability to pass environment variables to custom apps

### ISSUE THREAD

**Issue by aktech** [nebari-dev/jhub-apps#79]
### Feature description

Currently custom apps aren't able to be created with user supplied environment variables.

### Value and/or benefit

To be able to deploy variety of apps with like for example to be able to supply something like:
- `BOKEH_ALLOW_WS_ORIGIN` for custom panel apps
- `OPENAI_API_KEY` for custom AI apps

**Comment by aktech** [comment]
We'll handle it in the next release @dharhas

**Comment by Adam-D-Lewis** [comment]
Maybe this could be done with conda store (not sure if it should)?  I believe conda envs support setting env vars (https://stackoverflow.com/a/62508395/9848141), but I'm not sure if conda store supports it.

**Comment by aktech** [comment]
>Maybe this could be done with conda store (not sure if it should)? 

jhub-apps should work with any JupyterHub installation and conda-store is specific to Nebari. By the way I have just added it in the API in this PR: https://github.com/nebari-dev/jhub-apps/pull/107 (frontend is pending though)

**Comment by aktech** [comment]
This is done.
