### ISSUE TITLE
[ENH] - Enhance sharing permissions

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/jhub-apps#81]
### Feature description

Currently, if you have an app, its always "shared" with everyone meaning that they can SEE it. But in order to LOAD the app, the user must be in the `admin` group. 

We need a solution that doesn't require admin access to view shared apps

### Value and/or benefit

Everyone won't have to be in the admin group.

**Comment by aktech** [comment]
This was done: https://github.com/nebari-dev/jhub-apps/issues/11
