### ISSUE TITLE
Proposed Nebari Wireframes

### ISSUE THREAD

**Issue by anavzelaya** [nebari-dev/jhub-apps#94]
| Status            | Open for comments 💬 |
| ----------------- | --------------------------------------------------------------------------------------- |
| Author(s)         | Ana Zelaya                                                                           |
| Date Created      | 01-31-2024                                                                               |                                                                              |

# Proposed Nebari Wireframes

## Summary

Wireframes for Nebari Home page and Create App flow. Open for feedback!

![image](https://github.com/nebari-dev/jhub-apps/assets/158315724/333d9eca-1ef6-4285-834a-23223436c328)

![image](https://github.com/nebari-dev/jhub-apps/assets/158315724/c09545d0-cfd5-48c7-8fee-6ee00e56e97c)

**Comment by jbouder** [comment]
New layout implemented. Closing issue
